config:
    paths:
        'oro/constants': 'bundles/orosidebar/js/constants.js'
        'oro/model/sidebar': 'bundles/orosidebar/js/model/sidebar.js'
        'oro/model/widget': 'bundles/orosidebar/js/model/widget.js'
        'oro/view/sidebar': 'bundles/orosidebar/js/view/sidebar.js'
        'oro/view/widget': 'bundles/orosidebar/js/view/widget.js'
        'oro/view/icon': 'bundles/orosidebar/js/view/icon.js'
        'oro/view/widgetAdd': 'bundles/orosidebar/js/view/widgetAdd.js'
        'oro/view/widgetRemove': 'bundles/orosidebar/js/view/widgetRemove.js'
        'oro/view/widgetSetup': 'bundles/orosidebar/js/view/widgetSetup.js'
        'oro/collection/widget': 'bundles/orosidebar/js/collection/widget.js'
        'oro/template/sidebar': 'bundles/orosidebar/js/template/sidebar.html'
        'oro/template/widgetMin': 'bundles/orosidebar/js/template/widgetMin.html'
        'oro/template/widgetMax': 'bundles/orosidebar/js/template/widgetMax.html'
        'oro/template/icon': 'bundles/orosidebar/js/template/icon.html'
        'oro/template/widgetRemove': 'bundles/orosidebar/js/template/widgetRemove.html'
        'oro/template/widgetAdd': 'bundles/orosidebar/js/template/widgetAdd.html'
        'oro/widget/default': 'bundles/orosidebar/js/widget/default.js'
        'oro/widget/helloWorld': 'bundles/orosidebar/js/widget/helloWorld.js'

build:
    paths:
        'oro/template/sidebar': 'empty:'
        'oro/template/widgetMin': 'empty:'
        'oro/template/widgetMax': 'empty:'
        'oro/template/icon': 'empty:'
        'oro/template/widgetRemove': 'empty:'
        'oro/template/widgetAdd': 'empty:'