parameters:
#    oro_sidebar.example.class: Oro\Bundle\SidebarBundle\Example

services:
#    oro_sidebar.example:
#        class: %oro_sidebar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
